### ISSUE TITLE
Netplay-specific saves not working on Linux

### ISSUE THREAD

**Issue by Sukid** [FasterMelee/Ishiiruka#14]
When trying to play Netplay with Project M, netplay specific saves in Sys/Wii/title isn't working properly. It claims the save is corrupted and wants to create a new one, which it can't because obviously it's write protected. I was just using the one anther's ladder distributes.

This seems to be a linux and possibly mac specific issue, as this feature seems to work fine on Windows.

**Comment by SilverMight** [comment]
Also getting the same problem. Any possible fix? Chmod didn't help

**Comment by SilverMight** [comment]
Anything?

**Comment by Sukid** [comment]
Thanks for the chmod suggestion, though yeah didn't do much for me either. HOWEVER I did find something that worked! When running FM in a non-case-sensitive folder it worked just fine. Unfortunately you need a format a new Ext4 volume with the right parameters to enable that feature, but you do it like this:

sudo mkfs -t ext4 -E encoding=utf8 -L label /dev/sd[whatever]
When you mount the new partition make sure to sudo chown it so you have write permission.
Then on that new ext4 partition, open a terminal and type
mkdir FM
sudo chattr +F FM

Not sure if the sudo is necessary but just in case. adding the +F attribute makes the folder non-case-sensitive. Then just your build of FM into that. :)

This would probably also work on a Fat32 drive but can't store Brawl on that so...

**Comment by Sukid** [comment]
Oh. I messed up. I just re-compiled it locally without moving it to a non case sensitive dir and it still successfully started with the netplay save.
Pretty sure it was fixed by this commit:
https://github.com/FasterMelee/FasterMelee-installer/pull/56

@SilverMight ^ Reinstall with that and see what happens. Clear everything out beforehand. The AUR package still seems to have the issue but that script makes it work perfectly.

**Comment by SilverMight** [comment]
> Oh. I messed up. I just re-compiled it locally without moving it to a non case sensitive dir and it still successfully started with the netplay save.
> Pretty sure it was fixed by this commit:
> [FasterMelee/FasterMelee-installer#56](https://github.com/FasterMelee/FasterMelee-installer/pull/56)
> 
> @SilverMight ^ Reinstall with that and see what happens. Clear everything out beforehand. The AUR package still seems to have the issue but that script makes it work perfectly.

That worked great! No issues now, thanks for the fix
